### ISSUE TITLE
react-map-gl v3.0 Release Tracker

### ISSUE THREAD

**Issue by ibgreen** [uber/react-map-gl#233]
# Current plans for react-map-gl v3

### Event Handling
- [x] Separate Event Handling from Map (split into `StaticMap`, `MapControls` and `InteractiveMap`) 
- [x] Make react-map-gl independent of internal mapbox-gl files (`transform.js` no longer used in event handling).
- [x] Multitouch support (by adopting Hammer.js) (related: #232)
- [x] Add double-click to zoom (related: #2)
- [x] New event handling architecture (separate viewport updates from event handling registration)

Note: The new event handling classes will be “exported” as an experimental feature in react-map-gl v3.0.0 - we need more time to bake the API. Apps that want to do custom can still benefit considerably from the new design by copying code and making localized changes.

### Control Components - Zoom/Markers etc for mapbox parity
- [x] Marker
- [x] Popup
- [x] AttributionControl
- [x] NavigationControl

### Polish
- [ ] Clean up all examples
- [ ] Add coverage/coveralls integration + badge
- [ ] Go through open issues and review what can be fixed/closed
- [ ] Remove stage-2 from exhibits - should be as simple as possible
- [ ] Mention `create-react-app` issues in README
- [ ] Review code for size to make sure we don't add overhead to the dist
- [ ] Review `package.json` dependencies, make sure they are minimal
- [x] Update API to be more consistent (e.g. `onChangeViewport` -> `onViewportChange`) and add `console.warn` to old methods for deprecation.

### Documentation
- [x] Move existing docs (overlays) from current gh-pages to markdown files on master
- [x] Create new docs for the new React components (`Marker` etc)
- [ ] Create/Update docs for any undocumented overlays
- [ ] Create "User’s Guide"
- [x] Create "What’s New" Page
- [x] Create "Upgrade Guide" Page
- [x] Create documentation for `StaticMap`, `InteractiveMap` (naming?)

### Open Proposals
- [x] Deprecate `ScatterplotOverlay`, `DraggablePointsOverlay`, `ChoroplethOverlay`?
    - (`ChoroplethOverlay` already moved to examples, due to big `d3-geo` dependency)
    - We'd move the deprecated overlays to examples (so that they can be copied into apps that still use them during the upgrade process).
    - We'd keep exporting the more generic overlays: `SVGOverlay`, `CanvasOverlay`, `HTMLOverlay`
