### ISSUE TITLE
3.2 release checklist

### ISSUE THREAD

**Issue by Pessimistress** [uber/react-map-gl#431]
- [x] Test with all deck.gl examples
- [x] Fix example links on website
- [x] Update guide and what's new
- [x] Upgrade dependencies to prod releases
- [x] More robust test cases
